### ISSUE TITLE
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by tdoniger** [tbischler/PEAKachu#12]
Finished library initialization in 0.0007174015045166016 seconds.

** Converting reads to bed format for 2 libraries...
Process Process-1:
Traceback (most recent call last):
  File "/private/software/packages/miniconda2/envs/peakachu/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/software/packages/miniconda2/envs/peakachu/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/private/software/packages/miniconda2/envs/peakachu/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/private/software/packages/miniconda2/envs/peakachu/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/private/software/packages/miniconda2/envs/peakachu/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/private/software/packages/miniconda2/envs/peakachu/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
HYJLVBGX5_AP169_18s002168-1-1_Ibberson_lane1E2F16i12_sequenceAligned.sortedByCoord.out generated an exception: A process in the process pool was terminated abruptly while the future was running or pending.
HYJLVBGX5_AP169_18s002168-1-1_Ibberson_lane1E2F17i8_sequenceAligned.sortedByCoord.out generated an exception: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "/private/software/packages/miniconda2/envs/peakachu/bin/peakachu", line 161, in <module>
    sys.exit(main())
  File "/private/software/packages/miniconda2/envs/peakachu/bin/peakachu", line 140, in main
    args.func(controller)
  File "/private/software/packages/miniconda2/envs/peakachu/bin/peakachu", line 150, in adaptive_approach
    controller.adaptive_approach()
  File "/private/software/packages/miniconda2/envs/peakachu/lib/python3.6/site-packages/peakachulib/controller.py", line 131, in adaptive_approach
    adaptive.generate_combined_bed_file()
  File "/private/software/packages/miniconda2/envs/peakachu/lib/python3.6/site-packages/peakachulib/adaptive.py", line 85, in generate_combined_bed_file
    "reads"], fill_value=0)
KeyError: 'reads'

**Comment by tdoniger** [comment]
I think I fixed this problem by updating the connection.py to a fixed connection.py
