### ISSUE TITLE
ValueError: Buffer for this type not yet supported

### ISSUE THREAD

**Issue by hepcat72** [tbischler/PEAKachu#14]
I'm getting the following error from PEAKachu:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/bin/peakachu", line 161, in <module>
    sys.exit(main())
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/bin/peakachu", line 140, in main
    args.func(controller)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/bin/peakachu", line 150, in adaptive_approach
    controller.adaptive_approach()
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/site-packages/peakachulib/controller.py", line 160, in adaptive_approach
    self._calc_sig_peaks_adaptive(adaptive, size_factors)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/site-packages/peakachulib/controller.py", line 247, in _calc_sig_peaks_adaptive
    self._args.pairwise_replicates)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/site-packages/peakachulib/adaptive.py", line 282, in run_deseq2_analysis
    deseq2_runner = DESeq2Runner(count_df)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/site-packages/peakachulib/deseq2.py", line 11, in __init__
    r("suppressMessages(library(DESeq2))")
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 353, in __call__
    return conversion.ri2py(res)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py", line 139, in ri2py_vector
    res = numpy2ri.ri2py(obj)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/site-packages/rpy2/robjects/numpy2ri.py", line 159, in ri2py_sexp
    res = numpy.asarray(obj)
  File "/galaxy/galaxy-app/tool-dependencies/_conda/envs/mulled-v1-df158f7db8ef004e884a3706d733d0a108cdd0c74ff386f5830ed8d37c0f63ec/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: Buffer for this type not yet supported.
```

**Comment by hepcat72** [comment]
I just tried it in a separate install, same data, same command line call - same error:

```
Traceback (most recent call last):
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/bin/peakachu", line 161, in <module>
    sys.exit(main())
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/bin/peakachu", line 140, in main
    args.func(controller)
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/bin/peakachu", line 150, in adaptive_approach
    controller.adaptive_approach()
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/peakachulib/controller.py", line 160, in adaptive_approach
    self._calc_sig_peaks_adaptive(adaptive, size_factors)
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/peakachulib/controller.py", line 258, in _calc_sig_peaks_adaptive
    adaptive.run_analysis_without_replicates(size_factors)
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/peakachulib/adaptive.py", line 326, in run_analysis_without_replicates
    deseq2_runner = DESeq2Runner(self._peak_df[self._lib_names_list])
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/peakachulib/deseq2.py", line 11, in __init__
    r("suppressMessages(library(DESeq2))")
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 353, in __call__
    return conversion.ri2py(res)
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py", line 139, in ri2py_vector
    res = numpy2ri.ri2py(obj)
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/rpy2/robjects/numpy2ri.py", line 159, in ri2py_sexp
    res = numpy.asarray(obj)
  File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: Buffer for this type not yet supported.
```

**Comment by tbischler** [comment]
> I just tried it in a separate install, same data, same command line call - same error:
> 
> ```
> Traceback (most recent call last):
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/bin/peakachu", line 161, in <module>
>     sys.exit(main())
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/bin/peakachu", line 140, in main
>     args.func(controller)
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/bin/peakachu", line 150, in adaptive_approach
>     controller.adaptive_approach()
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/peakachulib/controller.py", line 160, in adaptive_approach
>     self._calc_sig_peaks_adaptive(adaptive, size_factors)
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/peakachulib/controller.py", line 258, in _calc_sig_peaks_adaptive
>     adaptive.run_analysis_without_replicates(size_factors)
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/peakachulib/adaptive.py", line 326, in run_analysis_without_replicates
>     deseq2_runner = DESeq2Runner(self._peak_df[self._lib_names_list])
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/peakachulib/deseq2.py", line 11, in __init__
>     r("suppressMessages(library(DESeq2))")
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 353, in __call__
>     return conversion.ri2py(res)
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/functools.py", line 807, in wrapper
>     return dispatch(args[0].__class__)(*args, **kw)
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/rpy2/robjects/pandas2ri.py", line 139, in ri2py_vector
>     res = numpy2ri.ri2py(obj)
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/functools.py", line 807, in wrapper
>     return dispatch(args[0].__class__)(*args, **kw)
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/rpy2/robjects/numpy2ri.py", line 159, in ri2py_sexp
>     res = numpy.asarray(obj)
>   File "/Genomics/grid/users/rleach/miniconda3/envs/peakachu/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
>     return array(a, dtype, copy=False, order=order)
> ValueError: Buffer for this type not yet supported.
> ```

This seems to be an incompatibility between numpy and rpy2 versions (see https://bitbucket.org/rpy2/rpy2/issues/572/valueerror-buffer-for-this-type-not-yet). Maybe try upgrading rpy2 or downgrading numpy.

**Comment by hepcat72** [comment]
OK, but how can I do that on galaxy? Everything is installed via Conda. Are the versions not pinned in the conda package?

**Comment by tbischler** [comment]
As far as I see these package versions are not pinned. You could either wait until the compatible rpy2 version is available or as a workaround manually install an older numpy via conda.
