### ISSUE TITLE
Combined BED file generation problem

### ISSUE THREAD

**Issue by tbischler** [tbischler/PEAKachu#15]
I tried running using the docker container from the conda distro on my mac, but now I get the following error:

```
2_93D_Adapter-trimmed_Quality_Filtered_and_Deduplicated_BAMs generated an exception: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "/usr/local/bin/peakachu", line 161, in <module>
    sys.exit(main())
  File "/usr/local/bin/peakachu", line 140, in main
    args.func(controller)
  File "/usr/local/bin/peakachu", line 150, in adaptive_approach
    controller.adaptive_approach()
  File "/usr/local/lib/python3.7/site-packages/peakachulib/controller.py", line 131, in adaptive_approach
    adaptive.generate_combined_bed_file()
  File "/usr/local/lib/python3.7/site-packages/peakachulib/adaptive.py", line 85, in generate_combined_bed_file
    "reads"], fill_value=0)
KeyError: 'reads'
```

_Originally posted by @hepcat72 in https://github.com/tbischler/PEAKachu/issues/14#issuecomment-525489939_

**Comment by tbischler** [comment]
As this is likely unrelated to your first problem I created another issue. Did you generate index files (*.bam.bai) via samtools for each of your BAM files, which are located in the same folder? If these are missing the BAM files cannot be parsed.

**Comment by hepcat72** [comment]
I think I did. I know I should have anyway. I’ll take a look tomorrow.
